# For an explanation of the options, see:
# https://delphyne.readthedocs.io/en/latest/config.html#main-configuration

database:
  drivername: 'postgresql'
  host: '127.0.0.1'  # (localhost)
  port: 5432
  database_name: 'ohdsi'
  username: 'postgres'
  password: 'postgres'
  query:

source_data_folder: './resources/synthetic_data'

schema_translate_map:
  cdm_schema: 'cdm'
  vocabulary_schema: 'vocab'

run_options:
  skip_vocabulary_loading: True
  skip_custom_vocabulary_loading: True
  skip_source_to_concept_map_loading: True
  write_reports: False

sql_parameters:
  source_schema: 'source_data'
  #placeholder: 'value'
